### ISSUE TITLE
build on mac os 10.9.5 failed

### ISSUE THREAD

**Issue by crazyhottommy** [raphael-group/comet#8]
Hi, I am doing this: 

```
cd comet/
python setup.py build
```

error 

ld: library not found for -lglib-2.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1

How can I resolve this?

Thank you
Ming Tang

**Comment by bournewu** [comment]
Just remove the requirement of glib-2.0 in the setup.py. The issue should now be resolved.
