### ISSUE TITLE
run_comet_permutation.py error

### ISSUE THREAD

**Issue by crazyhottommy** [raphael-group/comet#9]
I am testing coMet using the example data and an error occurred. running python run_comet.py  did not give me any error and a tsv and Json file were generated.

`python run_comet_permutation.py -o GBM -m example_datasets/gbm/GBM.m2 -np 100000 -t 4 -k 4 -N 1000000`

Note: The Multi-Dendrix Python module could not be found. Using only random initializations...
- Mutation data: 11027 genes x 261 patients
- Creating bipartite graph...
- Graph has 23241 edges among 11288 nodes.

Traceback (most recent call last):es... 1/100000

  File "run_comet_permutation.py", line 158, in <module>

```
if __name__ == "__main__": run( get_parser().parse_args(sys.argv[1:]) )
```

  File "run_comet_permutation.py", line 107, in run

```
mutations = C.permute_mutation_data(G, genes, patients, args.seed, args.Q)
```

  File "/Users/Tammy/github_repos/comet/comet/permute.py", line 97, in permute_mutation_data

```
A = np.array(biadjacency_matrix(G, row_order=genes, column_order=patients, dtype=np.int32), dtype=np.int32)
```

ValueError: setting an array element with a sequence.

Thank you for your help.

**Comment by matthewreyna** [comment]
I am able to reproduce this error on NetworkX 1.10.  The `biadjacency_matrix` function in NetworkX 1.9 returns a dense matrix, but the same function in NetworkX 1.10 returns a sparse matrix.  For a quick fix, you can replace

```
A = np.array(biadjacency_matrix(G, row_order=genes, column_order=patients, dtype=np.int32), dtype=np.int32)
```

with

```
A = np.array(biadjacency_matrix(G, row_order=genes, column_order=patients, dtype=np.int32).todense(), dtype=np.int32)
```

i.e., add `.todense()` after the `biadjacency_matrix` function.  We will issue an update shortly to accommodate both NetworkX 1.9 and 1.10.
